import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ProtectedRoute } from "@/components/ProtectedRoute";
import { Providers } from "./provider";
import { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Insight As A Service",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/Cloud-infoservice-icon.png?v=2",
        type: "image/png",
        sizes: "32x32",
      },
      {
        url: "/Cloud-infoservice-icon.png?v=2",
        type: "image/png",
        sizes: "16x16",
      },
      {
        url: "/Cloud-infoservice-icon.png?v=2",
        type: "image/png",
        sizes: "any",
      },
    ],
    apple: "/Cloud-infoservice-icon.png?v=2",
    shortcut: "/Cloud-infoservice-icon.png?v=2",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <Providers>
          
          <ProtectedRoute>
            {children}</ProtectedRoute>
        </Providers>
      </body>
    </html>
  );
}
